module.exports.elements = {
    a: {color: 'blue', 'text-decoration': 'underline'},
    abbr: {},
    address: {display: 'block', 'font-style': 'italic'},
    area: {display: 'none'},
    article: {display: 'block'},
    aside: {display: 'block'},
    audio: {},
    b: {'font-weight': 'bold'},
    base: {},
    bdi: {},
    bdo: {'unicode-bidi': 'bidi-override'},
    blockquote: {
        display: 'block', 'margin-left': '40px', 'margin-right': '40px',
        'margin-top': '1em', 'margin-bottom': '1em'
    },
    body: {
        display: 'block',
        margin: '8px'
    },
    br: {},
    button: {},
    canvas: { display: 'block' },
    caption: {display: 'table-captopn', 'text-align': 'cneter'},
    cite: {'font-style': 'italic'},
    code: {'font-family': 'monospace'},
    col: {display: 'table-column'},
    colgroup: { display: 'table-column-group' },

    ///Edited///

    dd: {display: 'block'},
    div: {display: 'block'},
    dl: {display: 'block'},
    dt: {display: 'block'},
    fieldset: {display: 'block'},
    figcaption: {display: 'block'},
    figure: {display: 'block'},
    footer: {display: 'block'},
    form: {display: 'block'},
    h1: {display: 'block', 'font-size': '2em', 'font-weight': 'bold'},
    h2: {display: 'block', 'font-size': '1.5em', 'font-weight': 'bold'},
    h3: {display: 'block', 'font-size': '1.17em', 'font-weight': 'bold'},
    h4: {display: 'block', 'font-weight': 'bold'},
    h5: {display: 'block', 'font-size': '0.83em', 'font-weight': 'bold'},
    h6: {display: 'block', 'font-size': '0.67em', 'font-weight': 'bold'},
    head: {display: 'none'},
    header: {display: 'block'},
    hr: {display: 'block', 'border-bottom-width': '1px', 'border-bottom-color': '#888888'},
    html: {display: 'none'},
    i: {'font-style': 'italic'},
    img: {display: 'inline-block'},
    li: {display: 'block'},
    main: {display: 'block'},
    nav: {display: 'block'},
    noscript: {display: 'block'},
    ol: {display: 'block'},
    p: {display: 'block'},
    pre: {display: 'block'},
    section: {display: 'block'},
    small: {'font-size': 'smaller'},
    source: {},
    span: {},
    strike: {'text-decoration': 'line-through'},
    strong: {'font-weight': 'bold'},
    style: {display: 'none'},
    sub: {'vertical-align': 'sub', 'font-size': 'smaller'},
    summary: {display: 'block'},
    sup: { 'vertical-align': 'sup', 'font-size': 'smaller' },
    table: {display: 'block'},
    tfoot: {display: 'block'},
    u: {'text-decoration': 'underline'},
    ul: {display: 'block'},
    var: {'font-style': 'italic'},
    video: {display: 'block'}
 };


 module.exports.attr2css = {
     size: e => ({ 'font-size': `${12 * Math.pow(1.25, e-2)}px`}),
     fontfamily: e => ({ 'font-family': e }),
     face: e => ({ 'font-family': e }),
     color: e => ({ 'color': e }),
     bgcolor: e => ({ 'background-color': e }),
     align: e => ({ 'text-align': e }),
     'hr:color': e => ({ 'border-bottom-color': e }),
 };
